import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, CloudSun, Loader2, Plus, Trash2 } from 'lucide-react';
import { appClient } from '@/api/appClient';
import { weatherIcon } from '@/lib/tripEngine';
import DestinationImage from '@/components/DestinationImage';
import { splitLocation } from '@/lib/placeImages';

export default function ItineraryList({ trip, stops, onStopsChanged }) {
  const days = useMemo(()=>[...new Set([...(stops||[]).map(s=>Number(s.day_number)), ...Array.from({length:trip.days||1},(_,i)=>i+1)])].sort((a,b)=>a-b),[stops,trip.days]);
  const [day,setDay]=useState(days[0]||1); const [busy,setBusy]=useState(''); const [showAdd,setShowAdd]=useState(false); const [form,setForm]=useState({time:'10:00',activity:'',notes:''});
  const dayStops=(stops||[]).filter(s=>Number(s.day_number)===Number(day)).sort((a,b)=>a.sequence-b.sequence); const loc=splitLocation(trip.destination);
  const move=async(s,dir)=>{ const idx=dayStops.findIndex(x=>x.id===s.id), j=idx+dir; if(j<0||j>=dayStops.length)return; setBusy(s.id); try{await appClient.entities.TripStop.bulkUpdate([{id:dayStops[idx].id,sequence:dayStops[j].sequence},{id:dayStops[j].id,sequence:dayStops[idx].sequence}]); await onStopsChanged?.();}finally{setBusy('');}};
  const remove=async(s)=>{setBusy(s.id);try{await appClient.entities.TripStop.delete(s.id);await onStopsChanged?.();}finally{setBusy('');}};
  const add=async(e)=>{e.preventDefault();if(!form.activity.trim())return;setBusy('add');try{await appClient.entities.TripStop.create({trip_id:trip.id,day_number:Number(day),sequence:dayStops.length+1,time:form.time||'10:00',activity:form.activity.trim(),place_name:form.activity.trim(),notes:form.notes.trim()});setForm({time:'10:00',activity:'',notes:''});setShowAdd(false);await onStopsChanged?.();}finally{setBusy('');}};
  const weather=trip.weather_json; const weatherIndex=Math.max(0,Number(day)-1);
  return <section className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{days.map(d=><button key={d} onClick={()=>setDay(d)} className={`rounded-xl border px-4 py-2.5 font-mono text-xs ${day===d?'border-primary bg-primary text-primary-foreground':'border-border bg-card text-muted-foreground'}`}>Day {d}</button>)}</div>
    {weather?.time?.[weatherIndex] ? <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 text-sm shadow"><CloudSun className="h-4 w-4 text-primary"/><strong>{weather.time[weatherIndex]}</strong><span>{weatherIcon(weather.weathercode?.[weatherIndex])}</span><span className="text-muted-foreground">{Math.round(weather.temperature_2m_min?.[weatherIndex])}°–{Math.round(weather.temperature_2m_max?.[weatherIndex])}°C · saved forecast</span></div> : null}
    <div className="space-y-3">{dayStops.map((s,i)=><article key={s.id} className="overflow-hidden rounded-2xl bg-card text-card-foreground shadow-xl sm:flex"><DestinationImage place={s.place_name||s.activity} city={loc.city} state={loc.state} country={trip.country||''} variant="thumb" className="h-36 w-full sm:h-auto sm:w-44" /><div className="min-w-0 flex-1 p-5"><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-[10px] uppercase tracking-wide text-[#1E6B69]">{s.time||'Flexible'} · Stop {i+1}</div><h3 className="mt-1 font-heading text-xl font-semibold">{s.activity}</h3></div><div className="flex items-center gap-1"><button disabled={busy===s.id||i===0} onClick={()=>move(s,-1)} className="rounded-lg border border-border p-2 disabled:opacity-30"><ChevronUp className="h-4 w-4"/></button><button disabled={busy===s.id||i===dayStops.length-1} onClick={()=>move(s,1)} className="rounded-lg border border-border p-2 disabled:opacity-30"><ChevronDown className="h-4 w-4"/></button><button disabled={busy===s.id} onClick={()=>remove(s)} className="rounded-lg border border-border p-2 text-[#C15B3E]"><Trash2 className="h-4 w-4"/></button></div></div>{s.rating ? <div className="mt-2 text-xs text-primary">★ {s.rating}</div>:null}{s.notes?<p className="mt-3 text-sm leading-relaxed text-muted-foreground">{s.notes}</p>:null}{s.tip?<div className="mt-3 rounded-lg bg-primary/10 px-3 py-2 text-xs text-[#8a6731]">Tip: {s.tip}</div>:null}{busy===s.id?<div className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Loader2 className="h-3 w-3 animate-spin"/>Saving…</div>:null}</div></article>)}</div>
    <div className="rounded-2xl border border-dashed border-border bg-card/50 p-4">{showAdd?<form onSubmit={add} className="grid gap-3 md:grid-cols-[120px_1fr_1fr_auto]"><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})} className="ti-input"/><input required value={form.activity} onChange={e=>setForm({...form,activity:e.target.value})} placeholder="Activity / place" className="ti-input"/><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Notes" className="ti-input"/><button disabled={busy==='add'} className="rounded-lg bg-[#1E6B69] px-4 py-2 text-xs text-white">{busy==='add'?'Adding…':'Add'}</button></form>:<button onClick={()=>setShowAdd(true)} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><Plus className="h-4 w-4"/>Add a stop to Day {day}</button>}</div>
  </section>;
}
